plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id 'java'
    id 'com.github.johnrengelman.shadow' version '6.1.0'
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven {
        url "https://jitpack.io"
    } // For com.github.walkyst.JAADec-fork:jaadec-ext-aac & ibxm-fork:com.github.walkyst:ibxm-fork
    maven {
        url "https://maven.lavalink.dev/releases"
    } //youtube-source
}

test {
    useJUnitPlatform()
}

dependencies {
    // Use JUnit test framework.
    testImplementation 'junit:junit:4.13.2'

    // This dependency is used by the application.
    implementation 'com.google.guava:guava:31.0.1-jre'

    implementation 'net.dv8tion:JDA:5.3.1'
    implementation 'dev.arbjerg:lavaplayer:2.2.3'
    implementation 'dev.lavalink.youtube:common:1.12.0'
    implementation 'io.github.cdimascio:java-dotenv:5.2.2'
    implementation 'club.minnced:udpqueue-native-linux-x86-64:0.2.9' // adds linux 64bit
    implementation 'club.minnced:udpqueue-native-win-x86-64:0.2.9' // adds windows 64bit
}

task stage(dependsOn: ['build','shadowJar', 'clean', 'test'])
build.mustRunAfter clean
build.mustRunAfter test

jar {
    manifest{
        attributes 'Class-Path': '/libs/MusicBot-all.jar', 'Main-Class': 'musicbot.Bot'
    }
}

compileJava.options.encoding = 'UTF-8'
